#!/usr/bin/env python
#encoding: utf-8

def configure(ctx):
	pass

def build(ctx):
	src=ctx.get_sources(ctx.path.abspath())
	ctx.program(source=src,
							target='webvtt-parser',
							use='webvtt-static coverage profiler',
							name='webvtt-parser',
							features='c')
