#!/usr/bin/env python
#encoding: utf-8

def configure(ctx):
	pass

def build(ctx):
	src=ctx.get_sources(ctx.path.abspath())
	ctx.stlib(source=src,
						includes=ctx.path.abspath(),
						export_includes=ctx.path.abspath(),
						target='gtest',
						name='gtest',
						features='cxx',
						use='pthread')

