#!/usr/bin/env python
#encoding: utf-8

def configure(ctx):
	pass

def build(ctx):
	src=ctx.get_sources(ctx.path.abspath())
	#ctx.shlib(source=src,
	#					target='webvttxx',
	#					name='webvttxx',
	#					includes='../../include',
	#					export_includes='../../include',
	#					features='cxx',
	#					use='coverage profiler',
	#					defines='WEBVTT_BUILD_LIBRARY=1')

	ctx.stlib(source=src,
						target='webvttxx-static',
						name='webvttxx-static',
						includes='../../include',
						export_includes='../../include',
						features='cxx',
						use='coverage profiler',
						defines='WEBVTT_STATIC=1')

